### ISSUE TITLE
Only some parts of the configuration is loaded(not all cameras)

### ISSUE THREAD

**Issue by wackerr** [robmarkcole/HASS-amazon-rekognition#11]
Hi,

I have just started to use this component and it seems great but I have a problem with getting it to work with all cameras simultaneous.
I currently have 6 different cameras but if I add all of them to the configuration and do a reboot only 3-4 of them will added and for the rest I get this error in the log:
 

Error while setting up platform amazon_rekognition
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/amazon_rekognition/image_processing.py", line 69, in setup_platform
    client = boto3.client('rekognition', **aws_config) # Will not raise error.
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 827, in create_client
    endpoint_resolver = self._get_internal_component('endpoint_resolver')
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 694, in _get_internal_component
    return self._internal_components.get_component(name)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 906, in get_component
    del self._deferred[name]
KeyError: 'endpoint_resolver'

**Comment by robmarkcole** [comment]
Hi this has come up before (on the forums) so I created a specific issue for it https://github.com/robmarkcole/HASS-amazon-rekognition/issues/12
