### ISSUE TITLE
Multiple Cameras - Few Not Loading

### ISSUE THREAD

**Issue by jonathanzw** [robmarkcole/HASS-amazon-rekognition#17]
Running Hassio 0.103.4 
So I have 8 security cameras and upon restart 4-5 load perfectly and automations run smoothly, however 3-4 don't load. If I reboot 4-5 times I MAY get lucky and have all 8 load. Here is the log of one of the fails:

2020-01-23 11:43:53 ERROR (MainThread) [homeassistant.components.image_processing] Error while setting up platform amazon_rekognition
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/amazon_rekognition/image_processing.py", line 143, in setup_platform
    client = boto3.client("rekognition", **aws_config)  # Will not raise error.
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 828, in create_client
    endpoint_resolver = self._get_internal_component('endpoint_resolver')
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 695, in _get_internal_component
    return self._internal_components.get_component(name)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 907, in get_component
    del self._deferred[name]
KeyError: 'endpoint_resolver'

Any thoughts?

**Comment by robmarkcole** [comment]
duplicate of https://github.com/robmarkcole/HASS-amazon-rekognition/issues/12
