### ISSUE TITLE
Did a fresh install and get an error

### ISSUE THREAD

**Issue by moskovskiy82** [robmarkcole/HASS-amazon-rekognition#90]
HASSOS installation on top of Ubuntu 20.04

Logger: homeassistant.components.image_processing
Source: custom_components/amazon_rekognition/image_processing.py:232
Integration: Обработка изображения (documentation, issues)
First occurred: 9:36:44 (1 occurrences)
Last logged: 9:36:44

```
Error while setting up amazon_rekognition platform for image_processing
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/amazon_rekognition/image_processing.py", line 232, in setup_platform
    client = boto3.client("rekognition", **aws_config)
  File "/usr/local/lib/python3.8/site-packages/boto3/__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/boto3/session.py", line 258, in client
    return self._session.create_client(
  File "/usr/local/lib/python3.8/site-packages/botocore/session.py", line 834, in create_client
    client = client_creator.create_client(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 79, in create_client
    service_model = self._load_service_model(service_name, api_version)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 116, in _load_service_model
    json_model = self._loader.load_service_model(service_name, 'service-2',
  File "/usr/local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/loaders.py", line 374, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/usr/local/lib/python3.8/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/loaders.py", line 279, in list_available_services
    api_versions = os.listdir(full_dirname)
OSError: [Errno 74] Bad message: '/usr/local/lib/python3.8/site-packages/botocore/data/ec2-instance-connect'
```

**Comment by robmarkcole** [comment]
Looks like it failed to install botocore, no idea why this would happen

**Comment by robmarkcole** [comment]
no reply, closing
