### ISSUE TITLE
Investigate replacing custom Point and Box classes with Shapely

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/HASS-amazon-rekognition#92]
See 
- https://shapely.readthedocs.io/en/latest/manual.html#geometric-objects
- https://shapely.readthedocs.io/en/latest/manual.html#shapely.geometry.box

Do before https://github.com/robmarkcole/HASS-amazon-rekognition/issues/91

**Comment by robmarkcole** [comment]
done on master

**Comment by robmarkcole** [comment]
After this change I have an install error on synology:
```
Logger: homeassistant.util.package
Source: util/package.py:95
First occurred: 5:10:45 AM (1 occurrences)
Last logged: 5:10:45 AM

Unable to install package shapely: ERROR: Command errored out with exit status 1: command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-du5wo9rs/shapely/setup.py'"'"'; __file__='"'"'/tmp/pip-install-du5wo9rs/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-a1m_fwk_ cwd: /tmp/pip-install-du5wo9rs/shapely/ Complete output (11 lines): Failed `CDLL(libgeos_c.so.1)` Failed `CDLL(libgeos_c.so)` Traceback (most recent call last): File "<string>", line 1, in <module> File "/tmp/pip-install-du5wo9rs/shapely/setup.py", line 85, in <module> from shapely._buildcfg import geos_version_string, geos_version, \ File "/tmp/pip-install-du5wo9rs/shapely/shapely/_buildcfg.py", line 169, in <module> lgeos = load_dll('geos_c', File "/tmp/pip-install-du5wo9rs/shapely/shapely/_buildcfg.py", line 162, in load_dll raise OSError( OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'] ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by robmarkcole** [comment]
Based on the above experience, and that shapely is a significant new dependency, dont do this. Instead just implement the required features in python. Limit scope to four point polygon
